### ISSUE TITLE
Improve ability to use with concurrent builds

### ISSUE THREAD

**Issue by shevron** [codevise/jenkins-mysql-job-databases-plugin#3]
This is a very useful plugin, but for us it has one issue that I have not been able to work around easily: when more than one build of a job runs concurrently (esp when multi-branch jobs are used), they all share the same DB which ends up in non-consistent build / test environments. 

It would be a great improvment if the DB name could somehow include a unique job / build identifier - or even just allow the use of environment variables in the DB name. This way I could define my DB name something like `mydb_$EXECUTOR_NUMBER` to avoid conflicts (assuming one DB per machine). 

I'm not familiar with the Jenkins API, otherwise I would have issued a PR for this.

**Comment by tf** [comment]
Hey shevron,

that would be a nice addition and I'd be happy to accept a PR making this happen. 

The interpolation logic for database names would have to be used in the [builder](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql_builder.rb#L19) creating databases and the [publisher](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql_publisher.rb#L18) cleaning up. I'm not sure, though, how the required environment variables could be accessed. So far we [only set variables](https://github.com/codevise/jenkins-mysql-job-databases-plugin/blob/master/models/mysql_builder.rb#L44). Maybe the complete environment could be read that way, too? I don't know.

Maybe also @n-rodriguez has some input on this since he was working on some larger changes to the plugin some while back.

Cheers
Tim

**Comment by n-rodriguez** [comment]
Hi!

A good thing would be to use the BUILD_ID in the database name as it's supposed to be unique.
The difficulty I have is to retrieve the BUILD_ID within the plugin.

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/job-database-manager-mysql
https://github.com/jbox-web/job-database-manager-postgresql
